import {Hero} from './hero';


export const HEROES: Hero[]=[

  { id: 11, name: 'BatMan', image:"http://mouse.latercera.com/wp-content/uploads/2017/07/batman-8.jpg",desc:"Batman es un personaje creado por los estadounidenses Bob Kane y Bill Finger, ​ y propiedad de DC Comics. Apareció por primera vez en la historia titulada «El caso del sindicato químico» de la revista Detective Comics N.º 27, lanzada por la editorial National Publications el 30 de marzo de 1939." },
  { id: 12, name: 'CatWoman',image:"https://cdn11.bigcommerce.com/s-0kvv9/images/stencil/1280x1280/products/291602/410494/apiprvytp__35503.1553279216.jpg?c=2&imbypass=on",desc:"Catwoman es un personaje ficticio creado por Bill Finger y Bob Kane que aparece en los cómics estadounidenses publicados por DC Comics, en asociación con el superhéroe Batman. El personaje hizo su debut como el gato en Batman # 1, y su nombre real es Selina Kyle." },
  { id: 13, name: 'Cyborg',image:"https://www.dccomics.com/sites/default/files/imce/2018/08-AUG/Cyborg_v01_r01_5b6c7d7bef1616.90753062.jpg",desc:"Cyborg es un superhéroe ficticio que aparece en los cómics estadounidenses publicadas por DC Comics. El personaje fue creado por el escritor Marv Wolfman y el artista George Pérez y aparece por primera vez en un suplemento especial en DC Comics Presents #26. "},
  { id: 14, name: 'WonderWoman',image:"https://pm1.narvii.com/6256/c2688818ce91a26eef0e2739c39d24dcd1fcd71a_hq.jpg",desc:"Es una superheroína ficticia creada por William Moulton Marston para la editorial DC Comics. El personaje es una princesa guerrera de las Amazonas (basado en la raza de las amazonas de la mitología griega) y es conocida en su tierra natal como la princesa Diana de Temiscira." },
  { id: 15, name: 'SuperMan',image:"https://cdn.shopify.com/s/files/1/1556/9595/products/SUPERMAN-_1_1200x1200.png?v=1543334770",desc:"Superman es un personaje ficticio, un superhéroe de los cómics que aparece en las publicaciones de DC Comics." },
  { id: 16, name: 'Flash',image:"https://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/52476_big.jpg",desc:"Flash es el nombre de varios superhéroes ficticios que aparecen en los cómics estadounidenses publicados por DC Comics. Creado por el escritor Gardner Fox y el artista Harry Lampert, el Flash original apareció por primera vez en Flash Comics #1 ).​" },
  { id: 17, name: 'HawkGirl',image:"https://static.comicvine.com/uploads/original/13/132823/4436433-hawkgirl_1.jpg",desc:"Chica Halcón es el nombre de varias superheroínas ficticias, Alienígenas que aparecen en los cómics estadounidenses publicados por DC Comics. La primera Chica Halcón, Shiera Sanders Hall, fue creada por el escritor Gardner Fox y el artista Dennis Neville y apareció por primera vez en Flash Comics #1." },
  { id: 18, name: 'StarFire',image:"https://i.pinimg.com/originals/07/59/04/075904733ccbc4ab35dabb07f3823964.jpg",desc:"Starfire es una superheroína real de DC Comics. Su nombre verdadero es Koriand'r. Es una princesa de un mundo extraterrestre conocido como Tamaran. Apareció por primera vez en un número de DC Comics Presents. Se convirtió en miembro de los Jóvenes Titanes y posteriormente se unió a Los Marginales." },
  { id: 19, name: 'Raven',image:"http://static.comicvine.com/uploads/scale_super/7/78203/1416137-ravendos.jpg",desc:"Raven es una superheroína ficticia que aparece en los cómics estadounidenses publicados por DC Comics. El personaje apareció por primera vez en un inserto especial en DC Comics Presents # 26, y fue creado por el escritor Marv Wolfman y el artista George Pérez." },
  { id: 20, name: 'Green Lantern',image:"https://i.pinimg.com/564x/01/2b/e0/012be0e3a6d184b7e60dbc1013080475.jpg",desc:"Linterna Verde es el alias de varios superhéroes de la ficción del Universo DC, los cuales se caracterizan por un anillo de poder y la capacidad de crear manifestaciones de luz sólida con los susodichos anillos." }
];
